### PR TITLE
MF-688 - Fix CLI 'provision test' subcommand

### LINKED ISSUE #688: CLI "provision test" subcommand fails due to invalid Org UUID
Currently, `mainfluxlabs-cli provision test` attempts to create a new Group belonging to non-existent Org with ID `"1"`, leading to the following errors:

```
mainfluxlabs-auth-db           | 2025-06-20 14:37:26.529 UTC [28] ERROR:  invalid input syntax for type uuid: "1"
mainfluxlabs-auth-db           | 2025-06-20 14:37:26.529 UTC [28] STATEMENT:  SELECT id, name, owner_id, description, metadata, created_at, updated_at FROM orgs WHERE id = $1
mainfluxlabs-auth              | {"level":"warn","message":"Method get_owner_id_by_org_id for id 1 took 8.707512ms to complete with error: entity not found : ERROR: invalid input syntax for type uuid: \"1\" (SQLSTATE 22P02).","ts":"2025-06-20T14:37:26.529748882Z"}
mainfluxlabs-things            | {"level":"warn","message":"Method create_groups for groups [] took 15.431418ms to complete with error: rpc error: code = Internal desc = internal server error.","ts":"2025-06-20T14:37:26.530746369Z"}
```

### PR DESCRIPTION
**Pull request by bool3max**
This PR closes #688 by first provisioning a new Org before other resources: Groups, Profiles, and Things.

It also enhances the `SDK.CreateOrg()` method to return the ID of the newly created Org.

### CODE REVIEW

File: cli/provision.go [hunk 1]
```diff
@@ -112,11 +110,18 @@ var cmdProvision = []cobra.Command{
...
+				logError(err)
+				return
+			}
+
 			g := mfxsdk.Group{
 				Name: "gr",
 			}
 
-			grID, err := sdk.CreateGroup(g, orgID, ut)
+			grID, err := sdk.CreateGroup(g, orgId, ut)
```
Comment (manuio) [inline cli/provision.go]: Use always camel case with capitalized acronyms

**Review by manuio — CHANGES_REQUESTED** [review]

File: cli/provision.go (hunk 1 above)
Comment (bool3max) [reply cli/provision.go]: Just fixed in latest commit.

File: pkg/sdk/go/orgs.go [hunk 2]
```diff
@@ -11,36 +11,37 @@ import (
...
 	}
 	defer resp.Body.Close()
 
 	if resp.StatusCode != http.StatusCreated {
-		return errors.Wrap(ErrFailedCreation, errors.New(resp.Status))
+		return "", errors.Wrap(ErrFailedCreation, errors.New(resp.Status))
 	}
 
-	return nil
+	return strings.TrimPrefix(resp.Header.Get("Location"), fmt.Sprintf("/%s/", orgsEndpoint)), nil
```
Comment (manuio) [inline pkg/sdk/go/orgs.go]:
```
id := strings.TrimPrefix(resp.Header.Get("Location"), fmt.Sprintf("/%s/", orgsEndpoint))
return id, nil
```

**Review by manuio — CHANGES_REQUESTED** [review]

File: pkg/sdk/go/orgs.go (hunk 2 above)
Comment (bool3max) [reply pkg/sdk/go/orgs.go]: Fixed in latest commit.

**Review by manuio — APPROVED** [review]
LGTM
