### PR TITLE
MF-1092 - add per-service PageMetadata types and fix order query parameter validation

### LINKED ISSUE #836: Strip apiutil.PageMetadata of all unnecessary fields
Currently, the `apiutil.PageMetadata` struct is shared among multiple services, and yet it contains fields which are only used in a subset of services, or even only one service (such as the `Payload` field).

We should strip it of all unnecessary fields, and only keep essential ones, namely: `Total`, `Offset`, `Limit`, `Ord`, and `Dir`.

Services which require additional fields should define their own 'version' of the struct, and embed `apiutil.PageMetadata` within. This is way it's currently done in the `readers` service, for example.

The `readers` and `users` services for example currently define their own versions: `readers.PageMetadata`/`users.PageMetadata`, but they make no use of `apiutil.PageMetadata`, instead re-defining all essential fields and thus also not being able to make use of `apiutil.BuildPageMetadata` either.

### LINKED ISSUE #1092: Limited validation for "order" query parameter in apiutil.ValidatePageMetadata

### PR DESCRIPTION
**Pull request by bool3max**
`apiutil.PageMetadata` has been stripped down to just the essential pagination-related fields. Each service now define its own `PageMetadata` which contains only the pagination fields required by that service.

Services whose requests don't require any additional fields continue to use `apiutil.PageMetadata`.

---

### Fixed order query parameter validation

#1024 fixed only part of the problem by expanding the list of allowed columns in the database layer (in `dbutil.GetOrderQuery`), but it turns out that a similar issue exsisted in the HTTP API layer, namely in `apiutil.ValidatePageMetadata` which validated the `Order` field against a predefined set of values.

This PR reworks the way the `order` query parameter is validated and sanitized:

* Each service now itself defines a set of values it accepts for the `order` parameter.
    * This set of values is passed to the service's `PageMetadata` validation method to validate the parameter in the HTTP layer.
* `dbutil.GetOrderQuery` no longer validates the parameter. Instead, it matches it against a static list of orders, each of which is mapped to an SQL expression used in the ORDER BY clause. For now these are only the `"name"` and `"email"` orders which get mapped to `LOWER(name)` and `LOWER(email)` respectively.

Closes #1092. Closes #836.

### CODE REVIEW

File: consumers/alarms/api/http/requests.go [hunk 1]
```diff
@@ -1,12 +1,14 @@
...
 
 import (
+	"github.com/MainfluxLabs/mainflux/consumers/alarms"
 	"github.com/MainfluxLabs/mainflux/pkg/apiutil"
 )
 
 const (
 	minLen       = 1
 	maxLimitSize = 200
+	maxNameSize  = 254
```
Comment (majabirmancevic) [inline consumers/alarms/api/http/requests.go]: no need for `maxNameSize`, alarms dont have a `name` column

File: auth/api/http/orgs/transport.go [hunk 2]
```diff
@@ -74,8 +74,53 @@ func MakeHandler(svc auth.Service, mux *bone.Mux, tracer opentracing.Tracer, log
 	return mux
 }
 
+func buildOrgsPageMetadata(r *http.Request) (auth.PageMetadata, error) {
+	base, err := apiutil.BuildPageMetadata(r)
+	if err != nil {
+		return auth.PageMetadata{}, err
+	}
+	n, _ := apiutil.ReadStringQuery(r, apiutil.NameKey, "")
```
Comment (manuio) [inline auth/api/http/orgs/transport.go:83]: add a new line

File: auth/api/http/orgs/transport.go [hunk 3]
```diff
@@ -74,8 +74,53 @@ func MakeHandler(svc auth.Service, mux *bone.Mux, tracer opentracing.Tracer, log
...
+	m, _ := apiutil.ReadMetadataQuery(r, apiutil.MetadataKey, nil)
+	return auth.PageMetadata{
```
Comment (manuio) [inline auth/api/http/orgs/transport.go:86]: add a new line

File: auth/api/http/orgs/transport.go [hunk 4]
```diff
@@ -74,8 +74,53 @@ func MakeHandler(svc auth.Service, mux *bone.Mux, tracer opentracing.Tracer, log
...
+func buildOrgsPageMetadataFromBody(r *http.Request) (auth.PageMetadata, error) {
+	if r.Body == nil || r.ContentLength == 0 {
+		return auth.PageMetadata{
+			Offset: apiutil.DefOffset,
+			Limit:  apiutil.DefLimit,
+			Order:  apiutil.IDOrder,
+			Dir:    apiutil.DescDir,
+		}, nil
+	}
+	var pm auth.PageMetadata
```
Comment (manuio) [inline auth/api/http/orgs/transport.go:106]: add a new line

File: auth/api/http/orgs/transport.go [hunk 5]
```diff
@@ -74,8 +74,53 @@ func MakeHandler(svc auth.Service, mux *bone.Mux, tracer opentracing.Tracer, log
...
+	if err := json.NewDecoder(r.Body).Decode(&pm); err != nil {
+		return auth.PageMetadata{}, errors.Wrap(apiutil.ErrMalformedEntity, err)
+	}
+	if pm.Limit == 0 {
```
Comment (manuio) [inline auth/api/http/orgs/transport.go:111]: add a new line

File: auth/api/http/orgs/transport.go [hunk 6]
```diff
@@ -74,8 +74,53 @@ func MakeHandler(svc auth.Service, mux *bone.Mux, tracer opentracing.Tracer, log
...
+	if pm.Offset == 0 {
+		pm.Offset = apiutil.DefOffset
+	}
+	if pm.Order == "" {
+		pm.Order = apiutil.IDOrder
+	}
+	if pm.Dir == "" {
+		pm.Dir = apiutil.DescDir
+	}
+	return pm, nil
```
Comment (manuio) [inline auth/api/http/orgs/transport.go:127]: add a new line

File: auth/service.go [hunk 7]
```diff
@@ -38,6 +38,42 @@ var (
...
+	Email    string         `json:"email,omitempty"`
+}
+
+// Validate validates the page metadata.
+func (pm PageMetadata) Validate(maxLimitSize, maxNameSize int) error {
+	base := apiutil.PageMetadata{Offset: pm.Offset, Limit: pm.Limit, Order: pm.Order, Dir: pm.Dir}
+	if err := base.Validate(maxLimitSize, AllowedOrders); err != nil {
+		return err
+	}
+	if len(pm.Name) > maxNameSize {
```
Comment (manuio) [inline auth/service.go:72]: add a new line

File: auth/service.go [hunk 8]
```diff
@@ -38,6 +38,42 @@ var (
...
+		return apiutil.ErrNameSize
+	}
+	return nil
```
Comment (manuio) [inline auth/service.go:76]: add a new line

File: consumers/alarms/api/http/transport.go [hunk 9]
```diff
@@ -83,8 +83,23 @@ func MakeHandler(tracer opentracing.Tracer, svc alarms.Service, logger log.Logge
 	return r
 }
 
+func buildAlarmsPageMetadata(r *http.Request) (alarms.PageMetadata, error) {
+	base, err := apiutil.BuildPageMetadata(r)
+	if err != nil {
+		return alarms.PageMetadata{}, err
+	}
+	pl, _ := apiutil.ReadMetadataQuery(r, apiutil.PayloadKey, nil)
```
Comment (manuio) [inline consumers/alarms/api/http/transport.go:92]: add a new line

File: consumers/alarms/api/http/transport.go [hunk 10]
```diff
@@ -83,8 +83,23 @@ func MakeHandler(tracer opentracing.Tracer, svc alarms.Service, logger log.Logge
...
+	return alarms.PageMetadata{
```
Comment (manuio) [inline consumers/alarms/api/http/transport.go:94]: add a new line

File: consumers/notifiers/api/http/transport.go [hunk 11]
```diff
@@ -98,17 +98,56 @@ func decodeRequest(_ context.Context, r *http.Request) (any, error) {
...
-	pm, err := apiutil.BuildPageMetadata(r)
+func buildNotifiersPageMetadata(r *http.Request) (notifiers.PageMetadata, error) {
+	base, err := apiutil.BuildPageMetadata(r)
 	if err != nil {
-		return nil, err
+		return notifiers.PageMetadata{}, err
+	}
+	n, _ := apiutil.ReadStringQuery(r, nameKey, "")
+	m, _ := apiutil.ReadMetadataQuery(r, apiutil.MetadataKey, nil)
+	return notifiers.PageMetadata{
```
Comment (manuio) [inline consumers/notifiers/api/http/transport.go:110]: add a new line

File: consumers/notifiers/api/http/transport.go [hunk 12]
```diff
@@ -98,17 +98,56 @@ func decodeRequest(_ context.Context, r *http.Request) (any, error) {
 	return req, nil
 }
 
-func decodeListNotifiers(_ context.Context, r *http.Request) (any, error) {
-	pm, err := apiutil.BuildPageMetadata(r)
+func buildNotifiersPageMetadata(r *http.Request) (notifiers.PageMetadata, error) {
```
Comment (manuio) [inline consumers/notifiers/api/http/transport.go]: add new lines

File: consumers/notifiers/api/http/transport.go [hunk 13]
```diff
@@ -98,17 +98,56 @@ func decodeRequest(_ context.Context, r *http.Request) (any, error) {
...
+		Offset:   base.Offset,
+		Limit:    base.Limit,
+		Order:    base.Order,
+		Dir:      base.Dir,
+		Name:     n,
+		Metadata: m,
+	}, nil
+}
+
+func buildNotifiersPageMetadataFromBody(r *http.Request) (notifiers.PageMetadata, error) {
```
Comment (manuio) [inline consumers/notifiers/api/http/transport.go]: and here

File: consumers/notifiers/service.go [hunk 14]
```diff
@@ -17,6 +17,34 @@ import (
...
+	Offset   uint64         `json:"offset,omitempty"`
+	Limit    uint64         `json:"limit,omitempty"`
+	Order    string         `json:"order,omitempty"`
+	Dir      string         `json:"dir,omitempty"`
+	Name     string         `json:"name,omitempty"`
+	Metadata map[string]any `json:"metadata,omitempty"`
+}
+
+// Validate validates the page metadata.
+func (pm PageMetadata) Validate(maxLimitSize, maxNameSize int) error {
```
Comment (manuio) [inline consumers/notifiers/service.go:37]: and here

File: consumers/notifiers/service.go [hunk 15]
```diff
@@ -17,6 +17,34 @@ import (
...
+	base := apiutil.PageMetadata{Offset: pm.Offset, Limit: pm.Limit, Order: pm.Order, Dir: pm.Dir}
```
Comment (manuio) [inline consumers/notifiers/service.go]: Not sure that we need it but I'd call it `common`

File: downlinks/api/http/transport.go [hunk 16]
```diff
@@ -93,8 +93,23 @@ func decodeCreateDownlinks(_ context.Context, r *http.Request) (any, error) {
 	return req, nil
 }
 
+func buildDownlinksPageMetadata(r *http.Request) (downlinks.PageMetadata, error) {
```
Comment (manuio) [inline downlinks/api/http/transport.go]: add new lines

File: downlinks/service.go [hunk 17]
```diff
@@ -23,6 +23,33 @@ import (
...
+	Total  uint64 `json:"total,omitempty"`
+	Offset uint64 `json:"offset,omitempty"`
+	Limit  uint64 `json:"limit,omitempty"`
+	Order  string `json:"order,omitempty"`
+	Dir    string `json:"dir,omitempty"`
+	Name   string `json:"name,omitempty"`
+}
+
+// Validate validates the page metadata.
+func (pm PageMetadata) Validate(maxLimitSize, maxNameSize int) error {
```
Comment (manuio) [inline downlinks/service.go:42]: and here

**Review by manuio — CHANGES_REQUESTED** [review]

File: webhooks/api/http/transport.go [hunk 18]
```diff
@@ -104,8 +104,55 @@ func decodeRequest(_ context.Context, r *http.Request) (any, error) {
...
+func buildWebhooksPageMetadataFromBody(r *http.Request) (webhooks.PageMetadata, error) {
+	if r.Body == nil || r.ContentLength == 0 {
+		return webhooks.PageMetadata{
+			Offset: apiutil.DefOffset,
+			Limit:  apiutil.DefLimit,
+			Order:  apiutil.IDOrder,
+			Dir:    apiutil.DescDir,
+		}, nil
+	}
+	var pm webhooks.PageMetadata
```
Comment (manuio) [inline webhooks/api/http/transport.go:136]: add new blank lines here and in the rest of the method

File: users/api/http/users/transport.go [hunk 19]
```diff
@@ -197,70 +192,73 @@ func decodeListUsers(_ context.Context, r *http.Request) (any, error) {
...
+		pm:    pm,
 	}
 
 	if r.Body == nil || r.ContentLength == 0 {
 		return req, nil
 	}
 
-	var pm users.PageMetadata
-	if err := json.NewDecoder(r.Body).Decode(&pm); err != nil {
+	var bodyPM users.PageMetadata
```
Comment (manuio) [inline users/api/http/users/transport.go]: rename to `upm`

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — DISMISSED** [review]
LGTM

File: webhooks/api/http/transport.go [hunk 20]
```diff
@@ -120,7 +173,7 @@ func decodeListGroupWebhooks(_ context.Context, r *http.Request) (any, error) {
 }
 
 func decodeListThingWebhooks(_ context.Context, r *http.Request) (any, error) {
-	pm, err := apiutil.BuildPageMetadata(r)
+	pm, err := buildWebhooksPageMetadata(r)
```
Comment (majabirmancevic) [inline webhooks/api/http/transport.go]: can we avoid the service name in these helpers for building PM?
`buildWebhooksPageMetadata -> buildPageMetadata ?`
since we have separate helpers for services, maybe it's redundant?

File: things/api/http/profiles/transport.go [hunk 21]
```diff
@@ -180,7 +180,7 @@ func decodeViewByThing(_ context.Context, r *http.Request) (any, error) {
 	return req, nil
 }
 
-func buildProfilesPageMetadata(r *http.Request) (things.PageMetadata, error) {
+func buildPageMetadat(r *http.Request) (things.PageMetadata, error) {
```
Comment (majabirmancevic) [inline things/api/http/profiles/transport.go]: Metadata

**Review by majabirmancevic — DISMISSED** [review]

File: consumers/alarms/api/http/transport.go [hunk 22]
```diff
@@ -83,8 +83,25 @@ func MakeHandler(tracer opentracing.Tracer, svc alarms.Service, logger log.Logge
 	return r
 }
 
+func buildAlarmsPageMetadata(r *http.Request) (alarms.PageMetadata, error) {
```
Comment (manuio) [inline consumers/alarms/api/http/transport.go]: `buildPageMetadata`

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by majabirmancevic — APPROVED** [review]

**Review by manuio — APPROVED** [review]
LGTM
