### PR TITLE
MF-803 - Fix permission check in svc.ViewUser

### LINKED ISSUE #803: Missing permission/identity check in users.ViewUser
[`users.ViewUser`](https://github.com/MainfluxLabs/mainflux/blob/8e7e409541aa15216debbef5ab475a8f094c9aeb/users/service.go#L354) makes a call to `identify()` but it ignores the result, making any user able to retrieve the profile of any other user.

### PR DESCRIPTION
**Pull request by bool3max**
Simple. Fixes #803. To view a specific user's profile, the user making the request must be authenticated as either the Root Admin or as the user whose profile they're trying to view.

### CODE REVIEW

File: users/service.go [hunk 1]
```diff
@@ -352,10 +352,17 @@ func (svc usersService) Login(ctx context.Context, user User) (string, error) {
 }
 
 func (svc usersService) ViewUser(ctx context.Context, token, id string) (User, error) {
-	if _, err := svc.identify(ctx, token); err != nil {
+	currentUser, err := svc.identify(ctx, token)
```
Comment (manuio) [inline users/service.go]: Rename it `user`

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by majabirmancevic — APPROVED** [review]

**Review by manuio — APPROVED** [review]
LGTM
