### PR TITLE
MF-224 - Fix backup response and restore request in things service

### LINKED ISSUE #224: Fix backup response and restore request in things service
Fix `backup` response and `restore` request in things service.

### PR DESCRIPTION
**Pull request by zzokki81**
Fixed backup response and restore request

Resolves #224

### CODE REVIEW

File: things/postgres/channels.go [hunk 1]
```diff
@@ -488,7 +488,7 @@ func (cr channelRepository) retrieve(ctx context.Context, owner string, pm thing
 		olq = ""
 	}
 
-	q := fmt.Sprintf(`SELECT id, name, metadata FROM channels %s ORDER BY %s %s %s;`, whereClause, oq, dq, olq)
+	q := fmt.Sprintf(`SELECT id, name, owner, metadata FROM channels %s ORDER BY %s %s %s;`, whereClause, oq, dq, olq)
```
Comment (manuio) [inline things/postgres/channels.go]: Wait, we don't have to retrieve owner all the time. For example, for method `RetrieveByOwner` we don't need it.
Revert this and create a way to do it by passing an argument to `retrieve` method. Eventually, why not `SELECT * FROM channels;`?

**Review by manuio — CHANGES_REQUESTED** [review]

File: things/postgres/things.go [hunk 2]
```diff
@@ -400,7 +400,7 @@ func (tr thingRepository) retrieve(ctx context.Context, owner string, pm things.
 		olq = ""
 	}
 
-	q := fmt.Sprintf(`SELECT id, name, key, metadata FROM things %s ORDER BY %s %s %s;`, whereClause, oq, dq, olq)
+	q := fmt.Sprintf(`SELECT id, name, owner, key, metadata FROM things %s ORDER BY %s %s %s;`, whereClause, oq, dq, olq)
```
Comment (manuio) [inline things/postgres/things.go]: Same here

File: things/api/things/http/responses.go [hunk 3]
```diff
@@ -61,6 +60,7 @@ func (res shareThingRes) Empty() bool {
 type thingRes struct {
 	ID       string                 `json:"id"`
 	Name     string                 `json:"name,omitempty"`
+	Owner    string                 `json:"-"`
```
Comment (manuio) [inline things/api/things/http/responses.go]: This should probably be removed

File: things/api/things/http/responses.go [hunk 4]
```diff
@@ -127,6 +127,7 @@ func (res thingsPageRes) Empty() bool {
 type channelRes struct {
 	ID       string                 `json:"id"`
 	Name     string                 `json:"name,omitempty"`
+	Owner    string                 `json:"-"`
```
Comment (manuio) [inline things/api/things/http/responses.go]: same here

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM
