### PR TITLE
MF-996 - Fix backup and restore flow for JSON and SenML messages

### LINKED ISSUE #996: Fix backup/restore flow for messages

### PR DESCRIPTION
**Pull request by anna02272**
Resolves #996

### CODE REVIEW

File: readers/api/converters.go [hunk 1]
```diff
@@ -172,11 +172,11 @@ func getValue(ptr any, defaultValue string) string {
 	return defaultValue
 }
 
-func formatTime(ns int64, timeFormat string) string {
+func formatTime(ns int64, timeFormat string) any {
```
Comment (manuio) [inline readers/api/converters.go:175]: What's the point of doing this?

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM

**Review by duolok — APPROVED** [review]
