### PR TITLE
MF-50 - Fix setup tests.

### LINKED ISSUE #50: Fix setup tests in DB layer.
The tests do not run  in the DB layer due to a bad setup.Use `m.Run()` to run them. Check all services.

### PR DESCRIPTION
**Pull request by zzokki81**
Fix test not running.
Resolves #50

### CODE REVIEW

File: readers/influxdb/messages_test.go [hunk 1]
```diff
@@ -19,7 +20,7 @@ import (
 const (
 	testDB      = "test"
 	subtopic    = "topic"
-	msgsNum     = 1001
+	msgsNum     = 101
```
Comment (manuio) [inline readers/influxdb/messages_test.go]: revert

File: readers/influxdb/messages_test.go [hunk 2]
```diff
@@ -404,7 +406,7 @@ func TestListChannelMessagesJSON(t *testing.T) {
 		},
 	}
 	messages1 := json.Messages{
-		Format: format1,
+		Format: format5,
```
Comment (manuio) [inline readers/influxdb/messages_test.go]: revert

File: readers/mongodb/messages_test.go [hunk 3]
```diff
@@ -25,7 +25,7 @@ import (
 const (
 	testDB      = "test"
 	subtopic    = "subtopic"
-	msgsNum     = 1001
+	msgsNum     = 101
```
Comment (manuio) [inline readers/mongodb/messages_test.go]: revert

File: readers/postgres/messages_test.go [hunk 4]
```diff
@@ -20,7 +20,7 @@ import (
 
 const (
 	subtopic    = "subtopic"
-	msgsNum     = 1001
+	msgsNum     = 101
```
Comment (manuio) [inline readers/postgres/messages_test.go]: revert

**Review by manuio — CHANGES_REQUESTED** [review]

File: readers/influxdb/messages_test.go [hunk 5]
```diff
@@ -32,6 +33,7 @@ const (
 
 	format1 = "format1"
 	format2 = "format2"
+	format5 = "format5"
```
Comment (manuio) [inline readers/influxdb/messages_test.go]: remove this

File: readers/postgres/messages_test.go [hunk 6]
```diff
@@ -543,6 +543,8 @@ func TestListChannelMessagesJSON(t *testing.T) {
 func TestListAllMessagesSenML(t *testing.T) {
 	writer := pwriter.New(db)
 
+	_, err := db.Exec("DELETE FROM messages")
```
Comment (manuio) [inline readers/postgres/messages_test.go]: Use Sprintf here

File: readers/timescale/messages_test.go [hunk 7]
```diff
@@ -29,6 +29,8 @@ const (
 	msgName     = "temperature"
 	format1     = "format1"
 	format2     = "format2"
+	format3     = "format3"
+	format4     = "format4"
```
Comment (manuio) [inline readers/timescale/messages_test.go]: Remove this

File: readers/timescale/messages_test.go [hunk 8]
```diff
@@ -516,6 +518,9 @@ func TestListChannelMessagesJSON(t *testing.T) {
 func TestListAllMessagesSenML(t *testing.T) {
 	writer := twriter.New(db)
 
+	_, err := db.Exec("DELETE FROM messages")
```
Comment (manuio) [inline readers/timescale/messages_test.go]: Sprintf here

File: readers/timescale/messages_test.go [hunk 9]
```diff
@@ -900,16 +905,6 @@ func TestListAllMessagesJSON(t *testing.T) {
...
-			pageMeta: readers.PageMetadata{
-				Format: messages1.Format,
-				Offset: zeroOffset,
-				Limit:  limit,
-			},
-			page: readers.MessagesPage{
-				Messages: []readers.Message{},
-			},
-		},
 		"read messages last page": {
```
Comment (manuio) [inline readers/timescale/messages_test.go]: remove this test

**Review by manuio — CHANGES_REQUESTED** [review]

File: things/postgres/groups_test.go [hunk 10]
```diff
@@ -319,13 +322,13 @@ func TestRetrieveAll(t *testing.T) {
...
 		Metadata things.PageMetadata
 	}{
-		"retrieve all groups": {
-			Metadata: things.PageMetadata{
-				Total: n,
-				Limit: n,
-			},
-			Size: n,
-		},
+		// "retrieve all groups": {
```
Comment (manuio) [inline things/postgres/groups_test.go]: dead code?

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM
