### PR TITLE
MF-670 - Improve API response when attempting to remove Profile assigned to at least one Thing

### LINKED ISSUE #670: Improve API response when attempting to delete a Profile with at least one belonging Thing
Currently, attempting to delete a Profile which has at least one Thing assigned to it, using the [appropriate API endpoint](https://mainfluxlabs.github.io/docs/api/#delete-profile), results in a `500 Internal Server Error` response and an associated 

```
{"error":"failed to remove entity"}
```

error message. 

We should enhance the endpoint to respond with a more sensible status code and perhaps a more informative error message.

### PR DESCRIPTION
**Pull request by bool3max**
This PR resolves #670:

- `profileRepository.Remove()` now checks for a foreign key validation error after attempting to remove the profile(s), returning a `things.ErrProfileInUse` as appropriate
- The API endpoint for removing profiles (`DELETE /profiles/:id`) now responds in a more descriptive, user-friendly manner by:
    - Returning `409 Conflict` as the HTTP status code
    - The following JSON error in the body:
    ```
    {"error":"profile currently assigned to thing(s)"}
    ```

Questions:

* Is `409 Conflict` an appropriate status code to respond with in a case such as this one?

### CODE REVIEW

File: things/api/http/profiles/transport.go [hunk 1]
```diff
@@ -244,6 +244,8 @@ func encodeError(_ context.Context, err error, w http.ResponseWriter) {
 		w.WriteHeader(http.StatusUnprocessableEntity)
 	case errors.Contains(err, uuid.ErrGeneratingID):
 		w.WriteHeader(http.StatusInternalServerError)
+	case errors.Contains(err, things.ErrProfileInUse):
```
Comment (manuio) [inline things/api/http/profiles/transport.go]: Rename to `ErrProfileAssigned`

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM
