### PR TITLE
MF-131 - Fix CanAccessGroup org method

### LINKED ISSUE #131: Improve  CanAccessGroup org method
`CanAccessGroup`  is used to retrieve `orgs` where group is assigned. Improve this method and make it more readable.

### PR DESCRIPTION
**Pull request by zzokki81**
Fixed `CanAccessGroup` to check if there is `orgs` where group is assigned.

Resolves #131

### CODE REVIEW

File: auth/service.go [hunk 1]
```diff
@@ -603,13 +603,17 @@ func (svc service) CanAccessGroup(ctx context.Context, token, groupID string) er
 		return err
 	}
 
+	if len(op.Orgs) == 0 {
```
Comment (manuio) [inline auth/service.go]: The length check is going to be done in the for loop, if len(op.Orgs) is 0 it will be ignored. Better move the error at the end of the method

File: auth/service.go [hunk 2]
```diff
@@ -603,13 +603,17 @@ func (svc service) CanAccessGroup(ctx context.Context, token, groupID string) er
...
+		return errors.ErrAuthorization
+	}
+
 	for _, org := range op.Orgs {
 		if err := svc.canEditGroups(ctx, org.ID, user.ID); err != nil {
```
Comment (manuio) [inline auth/service.go]: `err == nil` The point is to know if it's ok for 1 org

**Review by manuio — CHANGES_REQUESTED** [review]

File: auth/service.go [hunk 3]
```diff
@@ -604,8 +604,9 @@ func (svc service) CanAccessGroup(ctx context.Context, token, groupID string) er
 	}
 
 	for _, org := range op.Orgs {
-		if err := svc.canEditGroups(ctx, org.ID, user.ID); err != nil {
-			return err
+		err := svc.canEditGroups(ctx, org.ID, user.ID)
```
Comment (manuio) [inline auth/service.go]: inline

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM
