### PR TITLE
MF-887 - Correctly translate failed gRPC service calls to HTTP responses

### LINKED ISSUE #887: Fix HTTP 500 returned for gRPC errors
The `errors.Contains` helper function did not properly recognize gRPC `PermissionDenied` (e.g., `rpc error: code = PermissionDenied desc = failed to perform authorization over the entity.`) and other wrapped errors, causing other services to return `500 Internal Server Error ` instead of `403 Forbidden`.

### PR DESCRIPTION
**Pull request by bool3max**
Resolves #887 by testing the error that arrives in the `encodeError` function of each service's HTTP layer for a gRPC `status.Status` error, mapping its `Code` to an appropriate HTTP response status code, and constructing the response JSON error using its attached `.Message()`.

### CODE REVIEW

File: pkg/apiutil/transport.go [hunk 1]
```diff
@@ -185,14 +230,29 @@ func EncodeError(err error, w http.ResponseWriter) {
...
 		w.WriteHeader(http.StatusInternalServerError)
 	}
 }
 
 func WriteErrorResponse(err error, w http.ResponseWriter) {
+	var errorMessage string
+
 	if errorVal, ok := err.(errors.Error); ok {
+		errorMessage = errorVal.Msg()
+	} else if st, ok := status.FromError(err); ok {
```
Comment (manuio) [inline pkg/apiutil/transport.go]: Use a switch case instead

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM

**Review by majabirmancevic — APPROVED** [review]
