### PR TITLE
MF-671 - Change error on invalid old password when changing password

### LINKED ISSUE #671: Change password returns 401 Unauthorized on wrong old password

### PR DESCRIPTION
**Pull request by anna02272**
Resolves #671

### CODE REVIEW

File: pkg/errors/types.go [hunk 1]
```diff
@@ -39,4 +39,7 @@ var (
 
 	// ErrMessage indicates an error converting a message to Mainflux message.
 	ErrMessage = New("failed to convert to Mainflux message")
+
+	// ErrInvalidPassword indicates that current password is invalid.
+	ErrInvalidPassword = New("invalid current password")
```
Comment (manuio) [inline pkg/errors/types.go:44]: Use this error instead of the one defined in apiutil. apiutil errors should be used onlyin api packages

**Review by manuio — CHANGES_REQUESTED** [review]

File: users/service.go [hunk 2]
```diff
@@ -441,7 +441,7 @@ func (svc usersService) ChangePassword(ctx context.Context, token, email, passwo
 	// Admin changes password for another user
 	case oldPassword == "" && email != "":
 		if err := svc.isAdmin(ctx, token); err != nil {
-			return errors.ErrAuthentication
+			return errors.ErrAuthorization
```
Comment (manuio) [inline users/service.go]: Could we use the error returned by isAdmin here?

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM
