### PR TITLE
MF-1159 - Fix converters: message timestamp

### LINKED ISSUE #1159: converters: message timestamp not being correctly read from "created" CSV field
Converters seem to currently treat the `"created"` CSV field specially, but it ends up as part of the message payload and not the message creation timestamp.

e.g. publishing the following CSV file:

```csv
created,data
12345,"data1"
```

Results in the following JSON message:

```json
{
    ...
    "created": <unix timestamp of message publish date>,
    "payload": {
        "created": 12345,
        "data": "data1"
    }
}
```

In other words the `created` CSV field isn't being correctly interpreted as the message timestamp.

### LINKED ISSUE #1166: Fix missing Content-Type header on error responses
apiutil.EncodeError does not send Content-Type: application/json

EncodeError calls w.WriteHeader() before WriteErrorResponse sets w.Header().Set("Content-Type", "application/json"). Since headers must be set before WriteHeader, the Content-Type header is silently dropped on all error responses across all services.

### PR DESCRIPTION
**Pull request by manuio**
Resolves #1159 
Resolves #1166

### CODE REVIEW

**Review by duolok — DISMISSED** [review]
LGTM

File: converters/service.go [hunk 1]
```diff
@@ -62,50 +62,64 @@ func (as *adapterService) PublishSenMLMessages(ctx context.Context, key string,
...
 	}
 	counter := 0
 	keys := csvLines[0][1:]
 	msgs := []map[string]any{}
-	createdIdx := slices.Index(csvLines[0], "created")
-	if createdIdx == -1 {
-		return ErrInvalidTimeField
-	}
-
+	createdIdx := slices.Index(csvLines[0], timeField)
```
Comment (bool3max) [inline converters/service.go]: Maybe rename it to `timeFieldIdx`?

**Review by duolok — APPROVED** [review]
LGTM

**Review by majabirmancevic — APPROVED** [review]
